### ISSUE TITLE
Gospel Checksums

### ISSUE THREAD

**Issue by johnandersen777** [johnandersen777/johnandersen777.github.io#1]
- https://johnandersen777.github.io/gospel_checksums/

## TODOs

- [x] Game Plan
- [ ] Decode the Decoding Process
  - [ ] [Chuck Missler - How We Got Our Bible](https://www.youtube.com/watch?v=5ZsZLDWWZMs)
    - [x] Transcribe - Love is the essence of the Father
    - [ ] Notes
    - [ ] To specs
    - [ ] To workflows
    - [ ] Matrixies
- [ ] Languages Required
  - [ ] Vulgate
  - [ ] Greek
  - [ ] Hebrew
- [ ] Texts
  - [ ] [Wisdom the Goddess](http://thenazareneway.com/Wisdom%20the%20Goddess.htm)
  - [ ] [Essene Gospel Of Peace: Book Two](https://www.essene.com/GospelOfPeace/peace2.html)
  - [ ] [The Gospel of the Holy Twelve](http://gospelofholytwelve.blogspot.com/)
  - [ ] [Coptic Gospels](https://www.gospels.net)
  - [ ] [Gospels](https://www.gutenberg.org/cache/epub/10/pg10.txt)

## Game Plan

For those gospels that checksum correctly weight at 100 for patterns to follow.
For those that do not checksum but align to the checksum training we weight positively.

For those that do not we know that's the work of deception. Weight those high for anti-pattern avoidance stuff at 100.

Other texts from non biblical sources we can assess and add to training data and weight sources on generations appropriately.

Use concept mapping stuff sent to analyze other texts.

## Decode the Decoding Process

```bash
python -m pip install --upgrade --force-reinstall git+https://github.com/openai/whisper.git
python -m pip install -U --force-reinstall 'https://github.com/yt-dlp/yt-dlp/archive/refs/heads/master.zip#egg=yt-dlp'

python -m yt_dlp --no-call-home --no-cache-dir -x --audio-format mp3 --add-metadata --audio-quality 0 --restrict-filenames --ignore-errors 'https://www.youtube.com/watch?v=5ZsZLDWWZMs'
```

### Notes

h adds the essence. enoch knew of the flood

## Texts

**Comment by johnandersen777** [comment]
Moved to https://github.com/johnandersen777/johnandersen777.github.io/discussions/3
